# Generated by Django 5.2 on 2026-08-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2_provider", "0025_pushed_authorization_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                    (
                        "urn:ietf:params:oauth:grant-type:jwt-bearer",
                        "JWT bearer (RFC 7523)",
                    ),
                ],
                max_length=44,
                verbose_name="authorization grant type",
            ),
        ),
    ]
