"""
Django settings for idp project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import environ

from oauth2_provider.core.utils import set_oauthlib_user_to_device_request_user, user_code_generator


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.FileAwareEnv(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, []),
    DATABASE_URL=(str, "sqlite:///db.sqlite3"),
    SECRET_KEY=(str, "django-insecure-vri27@j_q62e2it4$xiy9ca!7@qgjkhhan(*zs&lz0k@yukbb3"),
    OAUTH2_PROVIDER_OIDC_ENABLED=(bool, True),
    OAUTH2_PROVIDER_OIDC_RP_INITIATED_LOGOUT_ENABLED=(bool, True),
    OAUTH2_PROVIDER_DCR_ENABLED=(bool, True),
    # RFC 7523 §2.1 JWT bearer grant, demonstrated by the "e2e-jwt-bearer"
    # seeded application (see fixtures/e2e_seed.json).
    OAUTH2_PROVIDER_JWT_BEARER_GRANT_ENABLED=(bool, True),
    OAUTH2_PROVIDER_JWT_BEARER_AUDIENCES=(list, []),
    OAUTH2_PROVIDER_CIMD_ENABLED=(bool, False),
    OAUTH2_PROVIDER_CIMD_METADATA_FETCHER=(
        str,
        "oauth2_provider.authorization_server.cimd.SafeMetadataFetcher",
    ),
    OAUTH2_PROVIDER_OIDC_RSA_PRIVATE_KEY=(
        str,
        """
-----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEAtd8X/v8pddKt+opMJZrhV4FH86gBTMPjTGXeAfKkQVf7KDUZ
Ty90n+JMe2rvCUn+Nws9yy5vmtbkomQbj8Xs1kHJOVdCnH1L2HTkvM7BjTBmJ5vc
bA94IBmSf9jJIzfIJkepshRLcGllMvHPOYQiR+lJsj58FFDLZN4/182S21C8Ri0w
+63rT64SxiQkqt6h+E1w7V+tHQJKDZq3du1QctZVXiIr6Zs5BgTjTyRURoiqUVH0
WJ4dT2t4+Rg9mp3PBlVwTOqzw9xTcO8ke+ZdrIWP4euZuPIr/Dya5R7S2Ki8Nwag
ANGV+LghJilucuWzJlOBO8TlIVUwgUaGOqaDxMHx9P/nRLQ6vTKP81FUJ7gNv6oj
W+6No6nMhsESQ+thizvBYOgintZZoeBwpB8lebKvGJUeqRo6qhc5BeUEjAjsAgtP
sJrRNQ4t8PT8mP+2dw4sU7J5PBAtx+ZdZ9bcH/sNuohBj77+6WhyvjmeYIKgCgjO
TdZH9O+kUIMaX9mlB+WvoVsk32qensZG/CgXXa3rWyXPvOdA9aOE4V0GCv1JfWKK
OXA8aY5aUGy0VvOWXHWpft5begr8onCjNs9UR6fCdCvcrSuiHTvNpM37E6Xh4kV4
uMzjGaj5ZLBOAY3cYzFI6LNrK4/YJvzLi9jxI1sJG1ZMz8kCywuJISEq4LcCAwEA
AQKCAgBcnbV8l7gnVhhfA9pvNAYZJ67ad+3hh8fSefWqjEP1Orad7RxsZMBBQ16r
YvNDibi5kzHurEENWu2nfM9EUgifu3SbjMJRKsVa/3wUYj3ShpkfBpIjPWVxA1TF
YkJbeuakB8507zzTi/iLDvT2V0GV2Uk8SfGp7tMFFODyJq/om56lJhJRuGmidAT/
fhxmH2XgKp+dYiGoKihH8UgIeiWDtX5Xp5MxLWjGleqjvN5l5ObG7rM+BZbrgNFk
GGIWwNJSaWP853CQBz0+v6mWpuOBHar945quwjSACOTgVOgOiS7/3pHQmOqEdE/9
PRAP1sV6eP/Qzh3Y8ab3zlBAwddLmZi+8sVV/sJadEMciU6AR8ZInf2zWtmxh6Ft
TNXUrSmDjKId84wyYT+pDg8Vv04X8xMNLWAIYeBawOPasEiBiFVUqDGHciPMBbhb
XxZK7Noi8akzCLWouPkrW4pjpsd5xrllakGFAFPktLvc8ZRyz2InaQKqhaaU+is5
ykAeHpJHVxg1xFY0hX06i8pkjXQROhc7+GUuifxKvVcouCwlUiSxcHGQLqzGKnYE
fpCs9uGI8+XolEq637LyYaZ7zpWd8Ehiw4AEfE3oOVIQd4xAQ8YDJxUG1fUYQfF8
iD5VO2+WO7a9QfScFZK+UebHEEXQGq4+JNUlP0KSnSsp3J0XkQKCAQEA3Y0sE9sE
l8VTTW3oxKChmq18UKJchyXU3BMLFnvDAPweUTdtS0QUIsDQD2pCU7wQonWOpqUj
vMwlTZjyNo+9N0l2fqleha1phzgYFCfTsgJ6gcl82y/JUvsGqMglKOUKoCFW5UtM
kUO+P5S25GqiDc0qsO6FGKSOvJ5aJLYEpEK5ez2q9uyzSYbp5aUuKwLb11rX0HW9
JjkB7hL4OtHpJ9E9uAsOj4VIWpysmX3d8UIv1Uez8f+bilhCMShKk4U9xz8ZY2K4
YXdfFr83b1kQybIDzeXeOQ5NQ6myS5HiqBSYx9Iy7Y54605KVM0CzLCPS5fAAcbW
5wq1H32OtxRS4wKCAQEA0iZ24W30BIYIx65YseVbBNs4cJr9ppqCAqUGqAhW8xfe
q7Atd6KG+lXWVDj2tZzuoYeb0PLjQRsmOs8CVFUZT0ntH6YAUOpPW8l8tkrWTugp
7fCx2pR4r8aFAVb7Jkc41ojSvaYMbUClKf+JVtFPsY1ug7gNxizGjVnpAq66XX+X
76BVIpMEUivZcXos6/BrVM3seFYQg1pMZkjjO3q8lETnlT3LIYpPtRjaFSvcMaMy
1Cb4dGUz+xj8BM73bLDEJtHZEsyF6nEnurlE9rSbMui9XhckcC267e1qvIbAnKB9
JK5oJAM4L+xOylmvk71gdrul9Q9aT+QJGUXkPxwfHQKCAQBkMIQ/UmtISyb5u/to
eA+8yDmQqWvYfiY9g6se9sbfuiPnrH4TbG0Crlkor2/hOAn5vdnNyJ5ZsaQo7EKU
o/n4d5NLgkJJh3tSd+6DpuMX/AD0km6RHJIZoYWIbEJJtRJSCeGm/Z9Zjd4KGLGA
qCwyu5ZTvvmXhEs8RwwSz/FXawlAD0oyMiZ92LILdOBk+Pz77YvtLGFmWJ9jz1ZM
G0MqC3iysuVZx/dJatKu8vmcMcc51xwsEuB+9pywaD0Za0bdxM4xYKJrCTWKLtzd
0NRDseoAgbQ17x7Hu4Tyob1zLyVML+VyAlzyZEw+/xsF/849bBmbdBUZFIGGBRy1
9E3rAoIBAQCDs3dtb+stqpJ2Ed2kH4kbUgfdCkVM1CgGYEX7qL5VOvBhyNe10jWl
TYY04j47M06aDNKp8I5bjxg2YuWi1HI4Lqxc2Tv5ed6iN3PhCqWkbftZEy9jPQkl
n9RbMpfTNW95g+YO1LGVBp5745m+vw6ix3ArPH3lZMpKa76L39UMI5qkoma4dEqQ
9MohQ+BDPTkGvMcl40oWB9E5iRRfglwMz+IStddH/dZWOGz0N7iXox+HtaSfzYz2
IIJQwSRvCZjkez7/eQ20D5ZGfzWpJybckN+cyAQeCYrM8a2i2RB9GFdVVbgOWbYs
0nvOdMaEYHrD7nXjTuvahZ7uJ88TfhxBAoIBAG3ClX40pxUXs6kEOGZYUXHFaYDz
Upuvj8X2h6SaepTAAokkJxGOdeg5t3ohsaXDeV2WcNb8KRFmDuVtcGSo0mUWtrtT
RXgJT9SBEMl1rEPbEh0i9uXOaI8DWdBO62Ei0efeL0Wac7kxwBbObKDn8mQCmlWK
4nvzevqUB8frm9abjRGTOZX8QlNZcPs065vHubNJ8SAqr+uoe1GTb0qL7YkWT6vb
dBCCnF8FP1yPW8UgGVGSeozmIMaJwSpl2srZUMkN1KlqHwzehrOn9Tn2grA9ue/i
ipUMvb4Se0LDJnmFuv8v6gM6V4vyXkP855mNOiRHUOHOSKdQ3SeKrLlnR6I=
-----END RSA PRIVATE KEY-----
""",
    ),
    OAUTH2_PROVIDER_SCOPES=(dict, {"openid": "OpenID Connect scope"}),
    # DEFAULT_SCOPES and PKCE_REQUIRED are env-driven so the end-to-end
    # compliance suite can exercise flows that need extra scopes or need PKCE
    # relaxed/required per client, without changing the defaults used by
    # maintainers running the app by hand. Defaults preserve prior behaviour:
    # a single "openid" scope and PKCE required (django-oauth-toolkit default).
    OAUTH2_PROVIDER_DEFAULT_SCOPES=(list, ["openid"]),
    OAUTH2_PROVIDER_PKCE_REQUIRED=(bool, True),
    OAUTH2_PROVIDER_PKCE_REQUIRED_CLIENT_IDS=(list, []),
    OAUTH2_PROVIDER_ALLOWED_SCHEMES=(list, ["https", "http"]),
    # Cookie/CSRF posture is env-driven so the cross-site end-to-end layer can
    # serve this IdP over TLS with SESSION_COOKIE_SAMESITE=None -- required for
    # the OP session cookie to reach a third-party iframe at all, and only
    # honoured by browsers alongside Secure. The defaults reproduce Django's own
    # defaults, so plain-HTTP local runs are unaffected.
    SESSION_COOKIE_SAMESITE=(str, "Lax"),
    SESSION_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_SAMESITE=(str, "Lax"),
    CSRF_COOKIE_SECURE=(bool, False),
    CSRF_TRUSTED_ORIGINS=(list, []),
    # RFC 9700 compliance gates, env-driven so the e2e suite and the Docker
    # image can exercise both the legacy (False, the library default) and the
    # enforced (True) position of every gate without a code change.
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_PASSWORD_GRANT=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_PKCE_METHOD=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_ACCESS_TOKEN_TRANSPORT=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_AUTHZ_RESPONSE_ISS=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_TOKEN_STORAGE=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_REFRESH_TOKEN=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_REDIRECT_URI_SCHEME=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_REDIRECT_URI_MATCHING=(bool, False),
    OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_PKCE_REQUIRED=(bool, False),
    OAUTHLIB_INSECURE_TRANSPORT=(bool, "1"),
    STATIC_ROOT=(str, BASE_DIR / "static"),
    STATIC_URL=(str, "/static/"),
    # Operator-supplied template override directories, searched before the
    # bundled defaults. Empty by default so local dev and e2e use the
    # bundled templates; set TEMPLATES_DIRS (e.g. a mounted /templates) to
    # override individual templates in the distributable image.
    TEMPLATES_DIRS=(list, []),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE")
SESSION_COOKIE_SECURE = env("SESSION_COOKIE_SECURE")
CSRF_COOKIE_SAMESITE = env("CSRF_COOKIE_SAMESITE")
CSRF_COOKIE_SECURE = env("CSRF_COOKIE_SECURE")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    "idp.apps.IDPAppConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "oauth2_provider",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "idp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Override dirs first so operators can shadow individual templates,
        # then the bundled defaults shipped with this app.
        "DIRS": [*env("TEMPLATES_DIRS"), BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "idp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = env("STATIC_ROOT")
STATIC_URL = env("STATIC_URL")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# PKCE can be a bool or a callable taking the client_id. When a set of
# client_ids is supplied (OAUTH2_PROVIDER_PKCE_REQUIRED_CLIENT_IDS), PKCE is
# required only for those clients and relaxed for the rest; otherwise the plain
# bool default applies. This lets the e2e suite prove both "PKCE enforced" and
# "PKCE optional" behaviours against a single running IdP.
_pkce_required_default = env("OAUTH2_PROVIDER_PKCE_REQUIRED")
_pkce_required_client_ids = set(env("OAUTH2_PROVIDER_PKCE_REQUIRED_CLIENT_IDS"))


def pkce_required(client_id):
    if _pkce_required_client_ids:
        return client_id in _pkce_required_client_ids
    return _pkce_required_default


OAUTH2_PROVIDER = {
    "OAUTH2_VALIDATOR_CLASS": "idp.oauth.CustomOAuth2Validator",
    "OAUTH_DEVICE_VERIFICATION_URI": "http://127.0.0.1:8000/o/device",
    "OAUTH_PRE_TOKEN_VALIDATION": [set_oauthlib_user_to_device_request_user],
    "OAUTH_DEVICE_USER_CODE_GENERATOR": user_code_generator,
    "OAUTH_DEVICE_VERIFICATION_URI_COMPLETE": lambda x: f"http://127.0.0.1:8000/o/device?user_code={x}",
    "OIDC_ENABLED": env("OAUTH2_PROVIDER_OIDC_ENABLED"),
    "OIDC_RP_INITIATED_LOGOUT_ENABLED": env("OAUTH2_PROVIDER_OIDC_RP_INITIATED_LOGOUT_ENABLED"),
    # this key is just for out test app, you should never store a key like this in a production environment.
    "OIDC_RSA_PRIVATE_KEY": env("OAUTH2_PROVIDER_OIDC_RSA_PRIVATE_KEY"),
    # A callable (given here as an import string) lets the access token lifetime vary
    # per request -- see "Varying the access token lifetime per request" in the docs.
    "ACCESS_TOKEN_EXPIRE_SECONDS": "idp.oauth.access_token_expires_in",
    "SCOPES": env("OAUTH2_PROVIDER_SCOPES"),
    "DEFAULT_SCOPES": env("OAUTH2_PROVIDER_DEFAULT_SCOPES"),
    "PKCE_REQUIRED": pkce_required,
    "ALLOWED_SCHEMES": env("OAUTH2_PROVIDER_ALLOWED_SCHEMES"),
    "DCR_ENABLED": env("OAUTH2_PROVIDER_DCR_ENABLED"),
    # RFC 7523 §2.1 JWT bearer authorization grant.
    "JWT_BEARER_GRANT_ENABLED": env("OAUTH2_PROVIDER_JWT_BEARER_GRANT_ENABLED"),
    "JWT_BEARER_AUDIENCES": env("OAUTH2_PROVIDER_JWT_BEARER_AUDIENCES"),
    # RFC 9700 compliance gates (see docs/security.rst).
    "COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT": env("OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT"),
    "COMPLIANT_BCP_RFC9700_PASSWORD_GRANT": env("OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_PASSWORD_GRANT"),
    "COMPLIANT_BCP_RFC9700_PKCE_METHOD": env("OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_PKCE_METHOD"),
    "COMPLIANT_BCP_RFC9700_ACCESS_TOKEN_TRANSPORT": env(
        "OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_ACCESS_TOKEN_TRANSPORT"
    ),
    "COMPLIANT_BCP_RFC9700_AUTHZ_RESPONSE_ISS": env(
        "OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_AUTHZ_RESPONSE_ISS"
    ),
    "COMPLIANT_BCP_RFC9700_TOKEN_STORAGE": env("OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_TOKEN_STORAGE"),
    "COMPLIANT_BCP_RFC9700_REFRESH_TOKEN": env("OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_REFRESH_TOKEN"),
    "COMPLIANT_BCP_RFC9700_REDIRECT_URI_SCHEME": env(
        "OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_REDIRECT_URI_SCHEME"
    ),
    "COMPLIANT_BCP_RFC9700_REDIRECT_URI_MATCHING": env(
        "OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_REDIRECT_URI_MATCHING"
    ),
    "COMPLIANT_BCP_RFC9700_PKCE_REQUIRED": env("OAUTH2_PROVIDER_COMPLIANT_BCP_RFC9700_PKCE_REQUIRED"),
    # Open registration so the DCR endpoints can be exercised with curl; this
    # demo IdP is for local testing only — in production keep the default
    # IsAuthenticatedDCRPermission (or a custom permission class) instead.
    "DCR_REGISTRATION_PERMISSION_CLASSES": (
        "oauth2_provider.authorization_server.dcr.AllowAllDCRPermission",
    ),
    # Advertise RFC 7523 JWT client authentication (the seed data ships a
    # private_key_jwt demo application; see tests/app/README.md).
    "OIDC_TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED": [
        "client_secret_post",
        "client_secret_basic",
        "private_key_jwt",
        "client_secret_jwt",
    ],
    "OAUTH2_TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED": [
        "client_secret_post",
        "client_secret_basic",
        "private_key_jwt",
        "client_secret_jwt",
    ],
    "CIMD_ENABLED": env("OAUTH2_PROVIDER_CIMD_ENABLED"),
    # The e2e suite points this at idp.cimd.LoopbackMetadataFetcher, which can
    # fetch metadata documents from a plain-HTTP loopback server; production
    # deployments must keep the default SSRF-hardened fetcher.
    "CIMD_METADATA_FETCHER": env("OAUTH2_PROVIDER_CIMD_METADATA_FETCHER"),
}
# needs to be set to allow cors requests from the test app, along with ALLOWED_SCHEMES=["http"]
os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = env("OAUTHLIB_INSECURE_TRANSPORT")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        # log oauth2_provider issues to facilitate troubleshooting
        "oauth2_provider": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        # occasionally you may want to see what's going on in upstream in oauthlib
        # "oauthlib": {
        #     "handlers": ["console"],
        #     "level": "DEBUG",
        #     "propagate": False,
        # },
    },
}
